parameters:
- name: arch
  type: string
  values:
  - amd64
  - armhf
  - arm64
  default: amd64

- name: pool
  type: string
  values:
  - sonicbld
  - sonicbld-armhf
  - sonicbld-arm64
  - default
  default: default

- name: timeout
  type: number
  default: 60

- name: sonic_slave
  type: string

- name: sairedis_artifact_name
  type: string

- name: sairedis_artifact_project
  type: string
  default: 'build'

- name: sairedis_artifact_pipeline
  type: string
  default: 'Azure.sonic-sairedis'

- name: sairedis_artifact_branch
  type: string
  default: '$(BUILD_BRANCH)'

- name: sairedis_artifact_pattern
  type: string
  default: '**'

- name: swss_common_artifact_name
  type: string

- name: swss_common_branch
  type: string
  default: '$(BUILD_BRANCH)'

- name: artifact_name
  type: string

- name: archive_pytests
  type: boolean
  default: false

- name: archive_gcov
  type: boolean
  default: false

- name: common_lib_artifact_name
  type: string

- name: common_lib_artifact_project
  type: string
  default: 'build'

- name: common_lib_artifact_pipeline
  type: string
  default: 'Azure.sonic-buildimage.common_libs'

- name: common_lib_artifact_branch
  type: string
  default: '$(BUILD_BRANCH)'

- name: asan
  type: boolean
  default: false

jobs:
- job:
  displayName: ${{ parameters.arch }}
  timeoutInMinutes: ${{ parameters.timeout }}

  pool:
    ${{ if ne(parameters.pool, 'default') }}:
      name: ${{ parameters.pool }}
    ${{ else }}:
      vmImage: 'ubuntu-20.04'

  container:
    image: sonicdev-microsoft.azurecr.io:443/${{ parameters.sonic_slave }}:latest

  steps:
  - checkout: self
    clean: true
    submodules: true
  - script: |
      sudo apt-get install -y libhiredis0.14 libhiredis-dev
      sudo apt-get install -y libzmq5 libzmq3-dev
      sudo apt-get install -qq -y \
          libhiredis-dev \
          swig3.0
      sudo apt-get install -y libdbus-1-3
      sudo apt-get install -y libteam-dev \
          libteam5 \
          libteamdctl0
    displayName: "Install dependencies"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: build
      pipeline: Azure.sonic-swss-common
      artifact: ${{ parameters.swss_common_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/${{ parameters.swss_common_branch }}'
      path: $(Build.ArtifactStagingDirectory)/download/swsscommon
      patterns: |
        libswsscommon_1.0.0_${{ parameters.arch }}.deb
        libswsscommon-dev_1.0.0_${{ parameters.arch }}.deb
    displayName: "Download sonic swss common deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: ${{ parameters.sairedis_artifact_project }}
      pipeline: ${{ parameters.sairedis_artifact_pipeline }}
      artifact: ${{ parameters.sairedis_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/${{ parameters.sairedis_artifact_branch }}'
      path: $(Build.ArtifactStagingDirectory)/download/sairedis
      patterns: |
        ${{ parameters.sairedis_artifact_pattern }}/libsaivs_*.deb
        ${{ parameters.sairedis_artifact_pattern }}/libsaivs-dev_*.deb
        ${{ parameters.sairedis_artifact_pattern }}/libsairedis_*.deb
        ${{ parameters.sairedis_artifact_pattern }}/libsairedis-dev_*.deb
        ${{ parameters.sairedis_artifact_pattern }}/libsaimetadata_*.deb
        ${{ parameters.sairedis_artifact_pattern }}/libsaimetadata-dev_*.deb
        ${{ parameters.sairedis_artifact_pattern }}/syncd-vs_*.deb
    displayName: "Download sonic sairedis deb packages"
  - task: DownloadPipelineArtifact@2
    inputs:
      source: specific
      project: ${{ parameters.common_lib_artifact_project }}
      pipeline: ${{ parameters.common_lib_artifact_pipeline }}
      artifact: ${{ parameters.common_lib_artifact_name }}
      runVersion: 'latestFromBranch'
      runBranch: 'refs/heads/${{ parameters.common_lib_artifact_branch }}'
      path: $(Build.ArtifactStagingDirectory)/download/common
      patterns: |
        target/debs/buster/libnl-3-200_*.deb
        target/debs/buster/libnl-3-dev_*.deb
        target/debs/buster/libnl-genl-3-200_*.deb
        target/debs/buster/libnl-genl-3-dev_*.deb
        target/debs/buster/libnl-route-3-200_*.deb
        target/debs/buster/libnl-route-3-dev_*.deb
        target/debs/buster/libnl-nf-3-200_*.deb
        target/debs/buster/libnl-nf-3-dev_*.deb
        target/debs/buster/libyang_*.deb
    displayName: "Download common libs"
  - script: |
      set -ex
      cd download
      sudo dpkg -i $(find common -type f -name '*.deb')
      sudo dpkg -i $(find swsscommon -type f -name '*.deb')
      sudo dpkg -i $(find sairedis -type f -name '*.deb')
      cd ..
      rm -rf download
    workingDirectory: $(Build.ArtifactStagingDirectory)
    displayName: "Install libnl3, sonic swss common and sairedis"
  - script: |
      set -ex
      tar czf pytest.tgz tests
      cp -r pytest.tgz $(Build.ArtifactStagingDirectory)/
      if [ '${{ parameters.archive_gcov }}' == True ]; then
         export ENABLE_GCOV=y
      fi
      if [ '${{ parameters.asan }}' == True ]; then
         export ENABLE_ASAN=y
      fi
      ./autogen.sh
      dpkg-buildpackage -us -uc -b -j$(nproc) && cp ../*.deb .
    displayName: "Compile sonic swss"
  - publish: $(System.DefaultWorkingDirectory)/
    artifact: ${{ parameters.artifact_name }}
    displayName: "Archive swss debian packages"
  - publish: $(Build.ArtifactStagingDirectory)/
    artifact: sonic-swss-pytests
    displayName: "Archive swss pytests"
    condition: eq('${{ parameters.archive_pytests }}', true)
